import os

class Config(object):
    MODE = os.environ.get('MODE')
    APP_WEBHOOKS_URL = os.environ.get('APP_WEBHOOKS_URL')
    PIANO_API_URL = os.environ.get("PIANO_API_URL")
    PIANO_HOST = os.environ.get('PIANO_HOST')
    PIANO_APP_ID = os.environ.get('PIANO_APP_ID')
    PIANO_API_TOKEN = os.environ.get("PIANO_API_TOKEN")
    PIANO_PRIVATE_KEY = os.environ.get("PIANO_PRIVATE_KEY")
    PIANO_ESP_API_URL = os.environ.get("PIANO_ESP_API_URL")
    PIANO_ESP_API_KEY = os.environ.get("PIANO_ESP_API_KEY")
    PIANO_ESP_SITE_ID = os.environ.get("PIANO_ESP_SITE_ID")
    PIANO_ESP_REGISTERED_USERS_LIST = os.environ.get("PIANO_ESP_REGISTERED_USERS_LIST")
    PIANO_ESP_PLUS_USERS_LIST = os.environ.get("PIANO_ESP_PLUS_USERS_LIST")
    LV_PLUS_RESOURCE_ID = os.environ.get("LV_PLUS_RESOURCE_ID")
    LV_PLUS_COMPLIMENTARY_RESOURCE_ID = os.environ.get("LV_PLUS_COMPLIMENTARY_RESOURCE_ID")
    MVAULT_USERNAME = os.environ.get("MVAULT_USERNAME")
    MVAULT_PASSWORD = os.environ.get("MVAULT_PASSWORD")
    MVAULT_STATION_ID = os.environ.get("MVAULT_STATION_ID")
    MVAULT_KEY = os.environ.get("MVAULT_KEY")
    MVAULT_SECRET = os.environ.get("MVAULT_SECRET")
    MVAULT_API = os.environ.get("MVAULT_API")
    MVAULT_PASSPORT_MEMBERSHIP = os.environ.get("MVAULT_PASSPORT_MEMBERSHIP")
    CAMPAIGN_MONITOR_CLIENT_ID = os.environ.get("CAMPAIGN_MONITOR_CLIENT_ID")
    CAMPAIGN_MONITOR_API_KEY = os.environ.get("CAMPAIGN_MONITOR_API_KEY")
    CAMPAIGN_MONITOR_API_URL = os.environ.get("CAMPAIGN_MONITOR_API_URL")
    CAMPAIGN_MONITOR_REGISTERED_USERS_LIST = os.environ.get("CAMPAIGN_MONITOR_REGISTERED_USERS_LIST") #keep
    CAMPAIGN_MONITOR_PLUS_USERS_LIST = os.environ.get("CAMPAIGN_MONITOR_PLUS_USERS_LIST") #remove
    CAMPAIGN_MONITOR_PLUS_COMPLIMENTARY_USERS_LIST = os.environ.get("CAMPAIGN_MONITOR_PLUS_COMPLIMENTARY_USERS_LIST") #remove
    CAMPAIGN_MONITOR_ACTIVE_DONORS_REGULAR_PROD = os.environ.get("CAMPAIGN_MONITOR_ACTIVE_DONORS_REGULAR_PROD") #new
    LV_FREE_RESOURCE_ID = os.environ.get("LV_FREE_RESOURCE_ID") #BRC5TALA


